
<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('CG Pools '.strtoupper($this->sCoin).' Pool')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/font-awesome.min.css" rel="stylesheet">
    <link href="/css/datepicker3.css" rel="stylesheet">
    <link href="/css/styles.css" rel="stylesheet">

    <!--Custom Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--[if lt IE 9]>
	<script src="/js/html5shiv.js"></script>
	<script src="/js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="http://cgpools.io">
                <img src="<?= $this->basePath('/assets/images/logo.png') ?>" height="60" alt="CG" style="float:left; margin-right:6px; margin-top:-14px;"/> <label style="color:#53b685;">CG</label> Pools
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li <?php if($this->sActive == 'home') { echo 'class="active"'; } ?>><a href="<?= $this->url('home') ?>">Home</a></li>
                <?php if($this->sPoolMode == 'single') { ?>
                <li <?php if($this->sActive == 'help') { echo 'class="active"'; } ?>><a href="/application/help">Help</a></li>
                <li <?php if($this->sActive == 'blocks') { echo 'class="active"'; } ?>><a href="/application/blocks">Blocks
                        <?php
                        if($this->oBlocks->candidatesTotal > 0) {
                            echo '<span class="label label-info">'.$this->oBlocks->candidatesTotal.'</span>';
                        }
                        ?></a></li>
                <li <?php if($this->sActive == 'miners') { echo 'class="active"'; } ?>><a href="/application/miners">Miners</a></li>
                <li <?php if($this->sActive == 'payments') { echo 'class="active"'; } ?>><a href="/application/payments">Payments</a></li>
                <li <?php if($this->sActive == 'about') { echo 'class="active"'; } ?>><a href="/application/about">About</a></li>
                <?php } else { ?>

                <?php } ?>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    <?= $this->content ?>
</div>
<div class="container-fluid" style="background:#53b685;">
    <div class="col-md-12 text-center">
        <h3 style="color:#fff;">Stay in touch</h3>
    </div>
    <div class="col-md-4 text-center">
        <a href="https://discord.gg/bFsR5z" title="Join us on Discord" style="color:#fff;" target="_blank">
            <i class="fab fa-discord fa-4x"></i>
            <h5 style="color:#fff;">Join us on Discord</h5>
        </a>
    </div>
    <div class="col-md-4 text-center">
        <a href="https://discord.gg/bFsR5z" title="Follow us on Twitter" style="color:#fff;" target="_blank">
            <i class="fab fa-twitter-square fa-4x"></i>
            <h5 style="color:#fff;">Follow us on Twitter</h5>
        </a>
    </div>
    <div class="col-md-4 text-center">
        <a href="https://discord.gg/bFsR5z" title="Announcement Channel" style="color:#fff;" target="_blank"        >
            <i class="fab fa-telegram fa-4x"></i>
            <h5 style="color:#fff;">Announcement Channel</h5>
        </a>
    </div>
</div>
<hr/>
<footer>
    <p>&copy; <?= date('Y') ?> CG Pools by <a href="https://coin-garden.io" target="_blank" title="Visit CoinGarden Website">CoinGarden</a>. Contact us admin@cgpools.io - Powered by <a href="https://github.com/CoinGardenMining/php-web-pool" target="_blank" title="PHP Web Pool in Github">php-web-pool</a></p>
</footer>
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/chart.min.js"></script>
<script src="js/chart-data.js"></script>
<script src="js/easypiechart.js"></script>
<script src="js/easypiechart-data.js"></script>
<script src="js/bootstrap-datepicker.js"></script>
<script src="js/custom.js"></script>
<?= $this->inlineScript() ?>
</body>
</html>