<div class="col-sm-12 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Dashboard</li>
        </ol>
    </div><!--/.row-->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                About
            </h1>
        </div>
    </div><!--/.row-->

    <div class="row">
        <ul>
            <li>Lightning Fast Go Mining Pool Implementation</li>
            <li>Stable & Fast ZF3 Frontend</li>
        </ul>
        <br/>
        <br/>
    </div>
</div>
