<?php
/**
 * Created by PhpStorm.
 * User: jbinggeli
 * Date: 17.06.18
 * Time: 18:24
 */

function printHashes($iHash) {
    switch($iHash) {
        case $iHash <= 1000:
            return number_format($iHash,2).' H/s';
            break;
        case $iHash <= (1000*1000):
            return number_format($iHash/1000,2).' KH/s';
            break;
        case $iHash <= (1000*1000*1000):
            return number_format($iHash/(1000*1000),2).' MH/s';
            break;
        case $iHash <= (1000*1000*1000*1000):
            return number_format($iHash/(1000*1000*1000),2).' GH/s';
            break;
        default:
            break;
    }
}

?>
<div class="col-sm-12 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Dashboard</li>
        </ol>
    </div><!--/.row-->

    <div class="row">
        <div class="col-lg-12">
            <h1>Account <?=$sAccount?></h1>
            <b>Current Hashrate: <?=printHashes($aInfo->currentHashrate)?></b><br/>
            <b>Hashrate (3h): <?=printHashes($aInfo->hashrate)?></b>
            <h2>Workers (<?=count((array)$aInfo->workers)?>)</h2>
            <ul class="list-group">
                <?php

                if(count((array)$aInfo->workers) > 1) {
                    $aMiners = (array)$aInfo->workers;
                    foreach(array_keys($aMiners) as $sMiner) {
                        $oMiner = $aMiners[$sMiner];
                        ?>
                        <li class="list-group-item">
                            <?=$sMiner?> - <?=printHashes($oMiner->hr)?> -  <?=printHashes($oMiner->hr2)?> - <?=date('d.m.Y H:i:s',$oMiner->lastBeat)?>
                        </li>
                        <?php
                    }
                } else {
                ?>
                    <li class="list-group-item">
                        0 - <?=printHashes($aInfo->currentHashrate)?> -  <?=printHashes($aInfo->hashrate)?>
                    </li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>