<?php
/**
 * Created by PhpStorm.
 * User: jbinggeli
 * Date: 17.06.18
 * Time: 18:12
 */

function printHashes($iHash) {
    switch($iHash) {
        case $iHash <= 1000:
            return number_format($iHash,2).' H/s';
            break;
        case $iHash <= (1000*1000):
            return number_format($iHash/1000,2).' KH/s';
            break;
        case $iHash <= (1000*1000*1000):
            return number_format($iHash/(1000*1000),2).' MH/s';
            break;
        case $iHash <= (1000*1000*1000*1000):
            return number_format($iHash/(1000*1000*1000),2).' GH/s';
            break;
        default:
            break;
    }
}
?>
<div class="col-sm-12 main">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="#">
                    <em class="fa fa-home"></em>
                </a></li>
            <li class="active">Dashboard</li>
        </ol>
    </div><!--/.row-->

    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default ">
                <div class="panel-heading">
                    Miners
                    <span class="pull-right clickable panel-toggle panel-button-tab-left"><em class="fa fa-info-circle"></em></span></div>
                <div class="panel-body articles-container">
                <?php

                if(count($aInfo->miners) > 0) {
                    $aMiners = (array)$aInfo->miners;
                    foreach(array_keys($aMiners) as $sMiner) {
                        $oMiner = $aMiners[$sMiner];
                    ?>
                    <div class="article border-bottom">
                        <div class="col-xs-12">
                            <div class="row">
                                <div class="col-xs-2 col-md-2 date">
                                    <div class="large"><?=printHashes($oMiner->hr)?></div>
                                    <div class="text-muted">-</div>
                                </div>
                                <div class="col-xs-10 col-md-10">
                                    <h4><a href="/application/account/<?=$sMiner?>" title="View Account Details">
                                            <?=$sMiner?>
                                        </a></h4>
                                    <p>
                                        Last Share: <?=date('d.m.Y H:i:s',$oMiner->lastBeat)?>
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="clear"></div>
                    </div><!--End .article-->
                    <?php
                    }
                }
                ?>
                </div>
            </div>
        </div><!--/.col-->
    </div>
</div>